### ISSUE TITLE
Is this based on version 2?

### ISSUE THREAD

**Issue by rianjs** [aarondandy/Hunspell.NetCore#2]
If so, the license is the GNU LGPL, instead of the v1 tri-license.

**Comment by aarondandy** [comment]
This is based on version 1 so I plan to keep the not so great tri-license thing for this repository, which I am in the process of renaming: #3 . Hunspell 2 is still in the works and as keeping this code in line with another code base is a tricky manual process I think I will wait until they are done. If I or somebody else were to start the v2 porting work early though I'm thinking that should be a separate repository, maybe under the same umbrella though? Maybe not if somebody else beats me to it?
